title: Praca zaliczeniowa
description: Praca zaliczeniowa na Komunikację Techniczną
theme: just-the-docs

url: https://makwojwwa.github.io/PracaZaliczeniowa

aux_links:
  Template Repository: https://github.com/makwojwwa/PracaZaliczeniowa
